# Generated by Skyramp v1.3.30 on 2026-06-29 22:20:35.174613474 +0000 UTC m=+433.942239526
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output app_messages_lifecycle_integration_test.py \
# 		--output-dir /home/runner/work/gotify-testb-sut/gotify-testb-sut/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/gotify-testb-sut/gotify-testb-sut/tests/skyramp/scenario_app-messages-lifecycle.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8080")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Declaration of variables
    application = "1"

    # Request Body
    application_POST_request_body = r'''{
        "description": "Test application for ownership lifecycle",
        "name": "testapp-lifecycle"
    }'''

    # Execute Request
    application_POST_response = client.send_request(
        url=URL_localhost,
        path="/application",
        method="POST",
        body=application_POST_request_body,
        headers={"X-Gotify-Key": "SKYRAMP_PLACEHOLDER_TOKEN"}
    )

    # Generated Assertions
    assert application_POST_response.status_code == 201
    assert skyramp.get_response_value(application_POST_response, "name") == "testapp-lifecycle"
    assert skyramp.get_response_value(application_POST_response, "description") == "Test application for ownership lifecycle"
    assert skyramp.get_response_value(application_POST_response, "internal") == False
    assert skyramp.get_response_value(application_POST_response, "id") > 0
    assert skyramp.get_response_value(application_POST_response, "token") is not None

    # Execute Request
    message_GET_response = client.send_request(
        url=URL_localhost,
        path="/application/{application}/message",
        method="GET",
        headers={"X-Gotify-Key": "SKYRAMP_PLACEHOLDER_TOKEN"},
        path_params={"application": application}
    )

    # Generated Assertions
    assert message_GET_response.status_code == 200
    assert skyramp.get_response_value(message_GET_response, "paging.limit") == 100
    assert skyramp.get_response_value(message_GET_response, "paging.size") == 0
    assert skyramp.get_response_value(message_GET_response, "paging.next") == ""
    assert skyramp.get_response_value(message_GET_response, "messages") is not None
    assert skyramp.get_response_value(message_GET_response, "messages.0") is None

    # Execute Request
    message_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/application/{application}/message",
        method="DELETE",
        headers={"X-Gotify-Key": "SKYRAMP_PLACEHOLDER_TOKEN"},
        path_params={"application": application}
    )

    # Generated Assertions
    assert message_DELETE_response.status_code == 204


if __name__ == "__main__":
    test_integration()
