# Generated by Skyramp v1.3.30 on 2026-06-29 22:23:55.368874271 +0000 UTC m=+633.996714471
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output application_update_token_prefix_persists_integration_test.py \
# 		--output-dir /home/runner/work/gotify-testb-sut/gotify-testb-sut/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/gotify-testb-sut/gotify-testb-sut/tests/skyramp/scenario_application-update-token-prefix-persists.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8080")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Declaration of variables
    application = "1"

    # Request Body
    application_POST_request_body = r'''{
        "description": "Update prefix test",
        "name": "update-prefix-app-1751232001"
    }'''

    # Execute Request
    application_POST_response = client.send_request(
        url=URL_localhost,
        path="/application",
        method="POST",
        body=application_POST_request_body,
        headers={"X-Gotify-Key": os.getenv("SKYRAMP_TEST_TOKEN", "SKYRAMP_PLACEHOLDER_TOKEN")}
    )

    # Generated Assertions
    assert application_POST_response.status_code == 200
    assert skyramp.get_response_value(application_POST_response, "name") == "update-prefix-app-1751232001"
    assert skyramp.get_response_value(application_POST_response, "description") == "Update prefix test"
    assert skyramp.get_response_value(application_POST_response, "internal") == False
    assert skyramp.get_response_value(application_POST_response, "id") is not None
    assert skyramp.get_response_value(application_POST_response, "id") > 0
    assert skyramp.get_response_value(application_POST_response, "token") is not None
    assert skyramp.get_response_value(application_POST_response, "tokenPrefix") is not None
    assert skyramp.get_response_value(application_POST_response, "tokenPrefix") == skyramp.get_response_value(application_POST_response, "token")[:4]
    application = str(skyramp.get_response_value(application_POST_response, "id"))

    # Request Body
    application_application_PUT_request_body = r'''{
        "description": "Updated description",
        "name": "update-prefix-app-renamed-1751232001"
    }'''

    # Execute Request
    application_application_PUT_response = client.send_request(
        url=URL_localhost,
        path="/application/{application}",
        method="PUT",
        body=application_application_PUT_request_body,
        headers={"X-Gotify-Key": os.getenv("SKYRAMP_TEST_TOKEN", "SKYRAMP_PLACEHOLDER_TOKEN")},
        path_params={"application": application}
    )

    # Generated Assertions
    assert application_application_PUT_response.status_code == 200
    assert skyramp.get_response_value(application_application_PUT_response, "name") == "update-prefix-app-renamed-1751232001"
    assert skyramp.get_response_value(application_application_PUT_response, "description") == "Updated description"
    assert skyramp.get_response_value(application_application_PUT_response, "id") == skyramp.get_response_value(application_POST_response, "id")
    assert skyramp.get_response_value(application_application_PUT_response, "tokenPrefix") == skyramp.get_response_value(application_POST_response, "tokenPrefix")

    # Execute Request
    application_GET_response = client.send_request(
        url=URL_localhost,
        path="/application",
        method="GET",
        headers={"X-Gotify-Key": os.getenv("SKYRAMP_TEST_TOKEN", "SKYRAMP_PLACEHOLDER_TOKEN")}
    )

    # Generated Assertions
    assert application_GET_response.status_code == 200
    assert skyramp.get_response_value(application_GET_response, "3.id") == skyramp.get_response_value(application_POST_response, "id")
    assert skyramp.get_response_value(application_GET_response, "3.name") == "update-prefix-app-renamed-1751232001"
    assert skyramp.get_response_value(application_GET_response, "3.tokenPrefix") == skyramp.get_response_value(application_POST_response, "tokenPrefix")


if __name__ == "__main__":
    test_integration()
