# Generated by Skyramp v1.3.30 on 2026-06-29 22:23:40.631983298 +0000 UTC m=+619.259823528
# Command: skyramp generate contract rest http://localhost:8080/application \
# 		--api-schema /home/runner/work/gotify-testb-sut/gotify-testb-sut/docs/spec.json \
# 		--auth-header X-Gotify-Key \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output-dir /home/runner/work/gotify-testb-sut/gotify-testb-sut/tests/skyramp \
# 		--overwrite \
# 		--provider \
# 		--request-data {"name":"contract-app-1751232002","description":"Contract test for tokenPrefix field"} \
# 		--response-status-code 200 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8080")

# contract test for /application POST
def test_application_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["X-Gotify-Key"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    application_POST_request_body = r'''{
        "description": "Contract test for tokenPrefix field",
        "name": "contract-app-1751232002"
    }'''

    # Expected Response Body
    expected_application_POST_response_body = r'''{
        "createdAt": "2019-01-01T00:00:00Z",
        "description": "Backup server for the interwebs",
        "id": 5,
        "image": "image/image.jpeg",
        "internal": false,
        "name": "Backup Server",
        "sortKey": "a1"
    }'''

    # Execute Request
    application_POST_response = client.send_request(
        url=URL,
        path="/application",
        method="POST",
        body=application_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert application_POST_response.status_code == 200
    assert skyramp.check_schema(application_POST_response, expected_application_POST_response_body)
    assert skyramp.get_response_value(application_POST_response, "createdAt") is not None
    assert skyramp.get_response_value(application_POST_response, "description") is not None
    assert skyramp.get_response_value(application_POST_response, "id") is not None
    assert skyramp.get_response_value(application_POST_response, "name") == "contract-app-1751232002"
    assert skyramp.get_response_value(application_POST_response, "description") == "Contract test for tokenPrefix field"
    assert skyramp.get_response_value(application_POST_response, "internal") == False
    assert skyramp.get_response_value(application_POST_response, "defaultPriority") == 0
    assert skyramp.get_response_value(application_POST_response, "id") > 0
    assert skyramp.get_response_value(application_POST_response, "token") is not None
    assert skyramp.get_response_value(application_POST_response, "tokenPrefix") is not None
    assert skyramp.get_response_value(application_POST_response, "tokenPrefix") == skyramp.get_response_value(application_POST_response, "token")[:4]


if __name__ == "__main__":
    test_application_post()
