# Generated by Skyramp v1.3.30 on 2026-06-29 22:18:50.649335839 +0000 UTC m=+329.416961911
# Command: skyramp generate contract rest http://localhost:8080/application/{id}/message \
# 		--api-schema /home/runner/work/gotify-testb-sut/gotify-testb-sut/docs/spec.json \
# 		--auth-header X-Gotify-Key \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output application_message_get_404_contract_test.py \
# 		--output-dir /home/runner/work/gotify-testb-sut/gotify-testb-sut/tests/skyramp \
# 		--overwrite \
# 		--path-params id=99999 \
# 		--provider \
# 		--response-status-code 404 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8080")

# contract test for /application/{id}/message GET
def test_message_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["X-Gotify-Key"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    id = "99999"

    # Expected Response Body
    expected_message_GET_response_body = r'''{
        "error": "Unauthorized",
        "errorCode": 401,
        "errorDescription": "you need to provide a valid access token or user credentials to access this api"
    }'''

    # Execute Request
    message_GET_response = client.send_request(
        url=URL,
        path="/application/{id}/message",
        method="GET",
        headers=headers,
        path_params={"id": id},
        query_params={
            "limit": 100,
            "since": None
        }
    )

    # Generated Assertions
    assert message_GET_response.status_code == 404
    assert skyramp.check_schema(message_GET_response, expected_message_GET_response_body)
    assert skyramp.get_response_value(message_GET_response, "error") is not None
    assert skyramp.get_response_value(message_GET_response, "errorCode") == 404
    assert skyramp.get_response_value(message_GET_response, "errorDescription") is not None


if __name__ == "__main__":
    test_message_get()
