# Generated by Skyramp v1.3.30 on 2026-06-29 22:25:24.88577634 +0000 UTC m=+773.901576773
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output message_priority_filter_pagination_bug_integration_test.py \
# 		--output-dir /home/runner/work/gotify-testb-sut/gotify-testb-sut/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/gotify-testb-sut/gotify-testb-sut/tests/skyramp/scenario_message-priority-filter-pagination-bug.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8080")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Request Body
    application_POST_request_body = r'''{
        "name": "PaginationBugApp-1750000000"
    }'''

    # Execute Request
    application_POST_response = client.send_request(
        url=URL_localhost,
        path="/application",
        method="POST",
        body=application_POST_request_body,
        headers={"X-Gotify-Key": "SKYRAMP_PLACEHOLDER_TOKEN"}
    )

    # Generated Assertions
    assert application_POST_response.status_code == 201
    assert skyramp.get_response_value(application_POST_response, "name") == "PaginationBugApp-1750000000"
    assert skyramp.get_response_value(application_POST_response, "id") > 0
    assert skyramp.get_response_value(application_POST_response, "token") is not None

    # Request Body
    message_POST_request_body = r'''{
        "appid": 1,
        "message": "Older priority-5 message",
        "priority": 5,
        "title": "Priority5-OlderMsg"
    }'''

    # Request Body
    message_POST_1_request_body = r'''{
        "appid": 1,
        "message": "Newer priority-1 message 1",
        "priority": 1,
        "title": "Priority1-NewerMsg1"
    }'''

    # Request Body
    message_POST_2_request_body = r'''{
        "appid": 1,
        "message": "Newer priority-1 message 2",
        "priority": 1,
        "title": "Priority1-NewerMsg2"
    }'''

    # Request Body
    message_POST_3_request_body = r'''{
        "appid": 1,
        "message": "Newer priority-1 message 3",
        "priority": 1,
        "title": "Priority1-NewerMsg3"
    }'''

    # Request Body
    message_POST_request_body = r'''{
        "appid": 1,
        "message": "Older priority-5 message",
        "priority": 5,
        "title": "Priority5-OlderMsg"
    }'''

    # Execute Request
    message_POST_response = client.send_request(
        url=URL_localhost,
        path="/message",
        method="POST",
        body=message_POST_request_body,
        headers={"X-Gotify-Key": "SKYRAMP_PLACEHOLDER_TOKEN"}
    )

    # Generated Assertions
    assert message_POST_response.status_code == 200
    assert skyramp.get_response_value(message_POST_response, "priority") == 5
    assert skyramp.get_response_value(message_POST_response, "message") == "Older priority-5 message"
    assert skyramp.get_response_value(message_POST_response, "title") == "Priority5-OlderMsg"
    assert skyramp.get_response_value(message_POST_response, "id") > 0

    # Request Body
    message_POST_1_request_body = r'''{
        "appid": 1,
        "message": "Newer priority-1 message 1",
        "priority": 1,
        "title": "Priority1-NewerMsg1"
    }'''

    # Request Body
    message_POST_2_request_body = r'''{
        "appid": 1,
        "message": "Newer priority-1 message 2",
        "priority": 1,
        "title": "Priority1-NewerMsg2"
    }'''

    # Request Body
    message_POST_3_request_body = r'''{
        "appid": 1,
        "message": "Newer priority-1 message 3",
        "priority": 1,
        "title": "Priority1-NewerMsg3"
    }'''

    # Request Body
    message_POST_1_request_body = r'''{
        "appid": 1,
        "message": "Newer priority-1 message 1",
        "priority": 1,
        "title": "Priority1-NewerMsg1"
    }'''

    # Execute Request
    message_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/message",
        method="POST",
        body=message_POST_1_request_body,
        headers={"X-Gotify-Key": "SKYRAMP_PLACEHOLDER_TOKEN"}
    )

    # Generated Assertions
    assert message_POST_1_response.status_code == 200
    assert skyramp.get_response_value(message_POST_1_response, "priority") == 1
    assert skyramp.get_response_value(message_POST_1_response, "id") > 0

    # Request Body
    message_POST_2_request_body = r'''{
        "appid": 1,
        "message": "Newer priority-1 message 2",
        "priority": 1,
        "title": "Priority1-NewerMsg2"
    }'''

    # Request Body
    message_POST_3_request_body = r'''{
        "appid": 1,
        "message": "Newer priority-1 message 3",
        "priority": 1,
        "title": "Priority1-NewerMsg3"
    }'''

    # Request Body
    message_POST_2_request_body = r'''{
        "appid": 1,
        "message": "Newer priority-1 message 2",
        "priority": 1,
        "title": "Priority1-NewerMsg2"
    }'''

    # Execute Request
    message_POST_2_response = client.send_request(
        url=URL_localhost,
        path="/message",
        method="POST",
        body=message_POST_2_request_body,
        headers={"X-Gotify-Key": "SKYRAMP_PLACEHOLDER_TOKEN"}
    )

    # Generated Assertions
    assert message_POST_2_response.status_code == 200
    assert skyramp.get_response_value(message_POST_2_response, "priority") == 1
    assert skyramp.get_response_value(message_POST_2_response, "id") > 0

    # Request Body
    message_POST_3_request_body = r'''{
        "appid": 1,
        "message": "Newer priority-1 message 3",
        "priority": 1,
        "title": "Priority1-NewerMsg3"
    }'''

    # Request Body
    message_POST_3_request_body = r'''{
        "appid": 1,
        "message": "Newer priority-1 message 3",
        "priority": 1,
        "title": "Priority1-NewerMsg3"
    }'''

    # Execute Request
    message_POST_3_response = client.send_request(
        url=URL_localhost,
        path="/message",
        method="POST",
        body=message_POST_3_request_body,
        headers={"X-Gotify-Key": "SKYRAMP_PLACEHOLDER_TOKEN"}
    )

    # Generated Assertions
    assert message_POST_3_response.status_code == 200
    assert skyramp.get_response_value(message_POST_3_response, "priority") == 1
    assert skyramp.get_response_value(message_POST_3_response, "id") > 0

    # Execute Request
    message_GET_response = client.send_request(
        url=URL_localhost,
        path="/message",
        method="GET",
        headers={"X-Gotify-Key": "SKYRAMP_PLACEHOLDER_TOKEN"},
        query_params={
            "limit": ["2"],
            "priority": ["5"]
        }
    )

    # Generated Assertions
    assert message_GET_response.status_code == 200
    assert skyramp.get_response_value(message_GET_response, "paging.size") == 1
    assert skyramp.get_response_value(message_GET_response, "paging.limit") == 2
    assert len(skyramp.get_response_value(message_GET_response, "messages")) == 1
    assert skyramp.get_response_value(message_GET_response, "messages.0.priority") == 5
    assert skyramp.get_response_value(message_GET_response, "messages.1") is None


if __name__ == "__main__":
    test_integration()
