# Generated by Skyramp v1.3.30 on 2026-06-29 22:17:48.958540878 +0000 UTC m=+326.848699408
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output message_count_after_delete_integration_test.py \
# 		--output-dir /home/runner/work/gotify-testb-sut/gotify-testb-sut/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/gotify-testb-sut/gotify-testb-sut/tests/skyramp/scenario_message-count-after-delete.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8080")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["X-Gotify-Key"] = os.getenv("SKYRAMP_TEST_TOKEN")
    # Execute Request
    message_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/message",
        method="DELETE",
        headers=headers
    )

    # Generated Assertions
    assert message_DELETE_response.status_code == 200

    # Execute Request
    count_GET_response = client.send_request(
        url=URL_localhost,
        path="/message/count",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert count_GET_response.status_code == 200
    assert skyramp.get_response_value(count_GET_response, "count") == 0


if __name__ == "__main__":
    test_integration()
