# Generated by Skyramp v1.3.30 on 2026-06-29 22:17:32.450297129 +0000 UTC m=+310.340455669
# Command: skyramp generate contract rest http://localhost:8080/message/count \
# 		--auth-header X-Gotify-Key \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output message_count_get_contract_test.py \
# 		--output-dir /home/runner/work/gotify-testb-sut/gotify-testb-sut/tests/skyramp \
# 		--overwrite \
# 		--provider \
# 		--response-data {"count":0} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8080")

# contract test for /message/count GET
def test_count_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["X-Gotify-Key"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_count_GET_response_body = r'''{
        "count": 0
    }'''

    # Execute Request
    count_GET_response = client.send_request(
        url=URL,
        path="/message/count",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(count_GET_response, "20x")
    assert skyramp.check_schema(count_GET_response, expected_count_GET_response_body)
    assert skyramp.get_response_value(count_GET_response, "count") is not None
    assert count_GET_response.status_code == 200
    assert skyramp.get_response_value(count_GET_response, "count") >= 0


if __name__ == "__main__":
    test_count_get()
