# Generated by Skyramp v1.3.30 on 2026-06-29 22:25:29.455764691 +0000 UTC m=+778.471565134
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output message_priority_filter_no_match_integration_test.py \
# 		--output-dir /home/runner/work/gotify-testb-sut/gotify-testb-sut/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/gotify-testb-sut/gotify-testb-sut/tests/skyramp/scenario_message-priority-filter-no-match.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8080")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Request Body
    application_POST_request_body = r'''{
        "name": "NoMatchApp-1750000000"
    }'''

    # Execute Request
    application_POST_response = client.send_request(
        url=URL_localhost,
        path="/application",
        method="POST",
        body=application_POST_request_body,
        headers={"X-Gotify-Key": "SKYRAMP_PLACEHOLDER_TOKEN"}
    )

    # Generated Assertions
    assert application_POST_response.status_code == 201
    assert skyramp.get_response_value(application_POST_response, "name") == "NoMatchApp-1750000000"
    assert skyramp.get_response_value(application_POST_response, "id") > 0
    assert skyramp.get_response_value(application_POST_response, "token") is not None

    # Request Body
    message_POST_request_body = r'''{
        "appid": 1,
        "message": "A priority-5 message",
        "priority": 5,
        "title": "PriorityFiveMsg"
    }'''

    # Execute Request
    message_POST_response = client.send_request(
        url=URL_localhost,
        path="/message",
        method="POST",
        body=message_POST_request_body,
        headers={"X-Gotify-Key": "SKYRAMP_PLACEHOLDER_TOKEN"}
    )

    # Generated Assertions
    assert message_POST_response.status_code == 200
    assert skyramp.get_response_value(message_POST_response, "priority") == 5
    assert skyramp.get_response_value(message_POST_response, "message") == "A priority-5 message"
    assert skyramp.get_response_value(message_POST_response, "title") == "PriorityFiveMsg"
    assert skyramp.get_response_value(message_POST_response, "id") > 0

    # Execute Request
    message_GET_response = client.send_request(
        url=URL_localhost,
        path="/message",
        method="GET",
        headers={"X-Gotify-Key": "SKYRAMP_PLACEHOLDER_TOKEN"},
        query_params={"priority": ["99"]}
    )

    # Generated Assertions
    assert message_GET_response.status_code == 200
    assert skyramp.get_response_value(message_GET_response, "paging.size") == 0
    assert skyramp.get_response_value(message_GET_response, "paging.limit") == 100
    assert len(skyramp.get_response_value(message_GET_response, "messages")) == 0
    assert skyramp.get_response_value(message_GET_response, "messages.0") is None


if __name__ == "__main__":
    test_integration()
