# Generated by Skyramp v1.3.30 on 2026-06-29 22:17:35.012219219 +0000 UTC m=+312.902377759
# Command: skyramp generate contract rest http://localhost:8080/message/count \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output message_count_unauth_contract_test.py \
# 		--output-dir /home/runner/work/gotify-testb-sut/gotify-testb-sut/tests/skyramp \
# 		--overwrite \
# 		--provider \
# 		--response-status-code 401 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8080")

# contract test for /message/count GET
def test_count_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # No authentication header — testing 401 Unauthorized
    headers = {}

    # Execute Request
    count_GET_response = client.send_request(
        url=URL,
        path="/message/count",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert count_GET_response.status_code == 401
    assert skyramp.get_response_value(count_GET_response, "errorCode") == 401
    assert skyramp.get_response_value(count_GET_response, "error") is not None


if __name__ == "__main__":
    test_count_get()
